FROM alpine:latest

MAINTAINER Cat.1 docker@gansi.me


RUN apk update && apk add python3 python3-dev && \
    pip3 install shadowsocks && \
    ln -s /usr/lib/python3.6/site-packages/shadowsocks/server.py  shadowsocks

CMD ["ssserver", "-s", "0.0.0.0", "-p", "1289", "-k", "yourpasswd", "-m", "rc4-md5"]

