FROM ubuntu:16.04
MAINTAINER Cat.1 docker@gansi.me

RUN apt-get update && apt-get install -y software-properties-common 
RUN add-apt-repository ppa:max-c-lv/shadowsocks-libev -y
RUN apt-get update && apt install shadowsocks-libev  -y

CMD ss-server -s 0.0.0.0 -p 443 -k yourpasswd -m rc4-md5


